pipeline:
  name: tf-ec2
  identifier: tfec2
  projectIdentifier: terraformHarness
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubharness
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash
                      terraform init
                      terraform plan
                      terraform apply -auto-approve
